spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projetoavaliacoes
    username: postgres
    password: lucasDev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


